/**
 * GENERATED by scripts/generate-art-variants.sh — do not edit by hand.
 * Re-run after replacing placeholder art in public/art/.
 */

const BASE = `${import.meta.env.BASE_URL}art/`;

/* AVIF srcset per source name (density-appropriate widths). */
export const ART_SRCSET: Record<string, string> = {
  'hero.jpg': `
    ${BASE}hero-960.avif 960w,
    ${BASE}hero.avif 1672w
  `,
  'u001.jpg': `
    ${BASE}u001-540.avif 540w,
    ${BASE}u001-840.avif 840w,
    ${BASE}u001.avif 1086w
  `,
  'u002.jpg': `
    ${BASE}u002-540.avif 540w,
    ${BASE}u002-840.avif 840w,
    ${BASE}u002.avif 1086w
  `,
  'u003.jpg': `
    ${BASE}u003-540.avif 540w,
    ${BASE}u003-840.avif 840w,
    ${BASE}u003.avif 1086w
  `,
  'u004.jpg': `
    ${BASE}u004-540.avif 540w,
    ${BASE}u004-840.avif 840w,
    ${BASE}u004.avif 1086w
  `,
  'u005.jpg': `
    ${BASE}u005-540.avif 540w,
    ${BASE}u005-840.avif 840w,
    ${BASE}u005.avif 1086w
  `,
  'u006.jpg': `
    ${BASE}u006-540.avif 540w,
    ${BASE}u006-840.avif 840w,
    ${BASE}u006.avif 1086w
  `,
  'u007.jpg': `
    ${BASE}u007-540.avif 540w,
    ${BASE}u007-840.avif 840w,
    ${BASE}u007.avif 1086w
  `,
  'u009.jpg': `
    ${BASE}u009-540.avif 540w,
    ${BASE}u009-840.avif 840w,
    ${BASE}u009.avif 1086w
  `,
};

/* Inline blur-up placeholders — 24px WebP, sub-1KB each. */
export const ART_LQIP: Record<string, string> = {
  'hero.jpg': 'data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQACiZGFaQc0YttmtdgA6rmoAAP7y3oO3I+AWd1Fsfdpa1VcOx2DxeBqZ86tWV0hvY21yz7zhRSvRVW/lViJXACIl1nWzglUo5b0cIyYeCKlfjRfZMnZemB2Apn1Jcn0OnCRiqeLUI6HQPMQnFPSiF6CkO8ut15L/I/wEfhkJP4hCgKwgAAAA',
  'u001.jpg': 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABwBQCdASoYACAAPu1srVEppaQiqAqpMB2JQBUehp4d/he8AcALwX6nlp4sw9cTKwItIrgAAP74T+400FsO2z3q2JaMQGqs+uwlc97KhTvgmNJA3mKmfZlFvSyoqogy99jtvqXHAix5/43kOIknxTiRfgCh0ZF7CgrMbUAA',
  'u002.jpg': 'data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAADQBQCdASoYACAAPu1kqk2ppaQiMAgBMB2JYwC7ITuDBnqpNYLKY9PVRZn57VE3IKl0JIXc0jEAAP7pB+FHKGc7ofokDTI/PRB2j0s9w0gLuTJH0OX/KHxS9O0K4pKzCRWSdsZCTXuS+66tZXbpuhQ02jSgzw05u13Jt9F/7Lc5mbBdEig6DqUgUjfbUMElmr0H6yvrxaLM2nXX6Zbg72DoKFFTLrj6ipCCgH3sTSm8KpuY+O21yFKz8Lj5HUYZTV8M9uQxV4zKiuMcsNX1mxAA',
  'u003.jpg': 'data:image/webp;base64,UklGRigBAABXRUJQVlA4IBwBAACQBgCdASoYACAAPu1urlIppiQiqAgBMB2JZACsDiAGuJoFQRW+SNjgfX2k8PRXeDCz4OATud+/XFVOFR3MAP75TnR1O581ZTj82LcWh6oZoefQaV/WD8fJz8zguWQ5sQOA4EC4PRB9dX6gwpyAe6uNDzEzRt2RTxJ1nXW9lKDHgcMNQj/bAf4aVvtWBna+EZ989ym/iK5xIY+lw5yuu2u0gFlDZhiO66W3zorDnmo/aAf/ISLeFZc1uHP/7IrmnAkhqg7B/s7SI3Y7gagzf7i/so4aFIDXDtHcE83OraW81XFusSwlAuFcc8RFvFk+TdSqHFqu8TurBTJ6+OEzS3OEZ5QaoEsjW4QQ3xDfb85ueCzRa/gLaWqCikAAAA==',
  'u004.jpg': 'data:image/webp;base64,UklGRv4AAABXRUJQVlA4IPIAAACQBQCdASoYACAAPu1qqk8ppiOiMBgIATAdiUAXYDGbZErEsD2Pv//I5tDo1EoddLPwUd4XKAD+42mxh/r+tAkLg6/mlkcKXuxcTuerq0d9UH7E72O3Zx2pVfiJcKyym0rPTuLZktnkpH52DpIn9F5m1xdloT2EYwsmjQKzg99hvdoO9d+dZJo+mOP/LvnCNZmBGal3NWnAgqGB1EJUrcbFBePCcHUWopVXVTFHAaqGLdGVJWy76Mh9YuiyJwqywWJR5p4Ivl5hEXsUZpkm1gtVMIhgMCN5rIrMWfNTiUNVR7lRL++xFLXGIdRc4EO3NZeAAA==',
  'u005.jpg': 'data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAAAwBgCdASoYACAAPu1mq0+ppSOiMBgIATAdiWMArhwR+iH4gIxGyaSpG+eTcvylbWtW1dnYfuFrJ8kAAP7bmkgRzjdjZo99HSDocuPynJsx4ANbOosS5vU37JkTS3503U2i+ZgsVI/MwUuZDXuUxqjC8a2938rGkd2IiQWKuW45M+DqvD5uNbkTfhmAQ+E8hrHUcIPqZ1p3I43bt7Z4R5oHi0uX549Gk6l9px8BlACtB3naKve9jhV5gLqXkthqlOVYOuFhW2n+bxRpgQ4zNm/XW8AAgnICUBgAAA==',
  'u006.jpg': 'data:image/webp;base64,UklGRtIAAABXRUJQVlA4IMYAAAAQBgCdASoYACAAPu1ur1IppiQiqAgBMB2JYwC7AzLQdeKXTu2P9Duk6U/paCyYD8LcMC4stK2v5gAA/vtqusgPZRIQMRXebVc94V4biqBPdFbfSARCotxJeE30MFNXBJONhPHNu/Aw3VzUxsUfEtEiHMPenNpjjklpf4OppsoJhgqirhga1Z+JjnvXV3tYlPxgl2RE68Slbi2iCXb5Xyudkj6+JNJdj+8QZfk8RPIbHHmsfbJrDlFAlvICUAPXpZdaFIAAAAA=',
  'u007.jpg': 'data:image/webp;base64,UklGRhgBAABXRUJQVlA4IAwBAADwBQCdASoYACAAPu1qsFAppaSiqAqpMB2JZgCdL5O4QBrzglPQl7Xi8gtpT2sMw0qEA0NmhpSCAAD+7AsI5265uW26tzHmkJLiv9VgDlsnOFLmAHW2aS5Y5hiLHx3mcQ1w8IzFmNz3VVa02Z/zq+lXOZP07nQU82q27hufF9neK0bTXXJKIqR3fPW+uFlvOfvew5TjkgCKKfJ434huzVLAWOCig3OfiTkcPKRd2sGCuVXZ0+fuUhpBOsQzVrCJWAl0TU+JelBkW1hHrsybLPrDXRKEpcakWsGSKY0P0KZB68DkqK17a2ROOBHXPfJ0seZdvAtm4fp63h0yBRpm8LtWqd9N8T424ftiQAAA',
  'u009.jpg': 'data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAADQBQCdASoYACAAPu1qrFEppaQiqAqpMB2JaQALAATqzu9emaRMOEsm/ga7hJhjPnvNbU5zGV+oAP73fU4Igo4PW4XTyIElfuhMCk+G+7aQdzs3zO6lsnI9egSq6WkOpA0eIIa7BTptgJeyLuz2Sz9Z/uZ3kjAKPO9t9WpHX1SWDRmxTotykM67AERokyqTX7QoK2WWd2l8zNV7aLvBkjoOlhPrRFCFHKVSdmoWmbx+Mxtn9+U4yigqmAAAAA==',
};
