/* ---------------------------------------------------------------------------
   fonts.ts — the critical-font gate (DESIGN_AUDIT P0.1, second half).

   Preloading in index.html is not viable here: src-referenced CSS assets are
   content-hashed at build and the site deploys with base './', so a static
   <link rel="preload"> would 404 in one of the two environments. The gate is
   the stronger version of the same idea — the boot loader does not release
   until these faces are ready (capped), so the hero's first real paint is
   already in Machina. The faces themselves are generated by
   scripts/subset-fonts.mjs (9 faces, subset to this site's codepoints).

   document.fonts.load() resolves against the @font-face set itself, so the
   weight specs below mirror how the CSS matching resolves the site's actual
   requests (a 700 request on Machina resolves to the 800 face, etc.).
--------------------------------------------------------------------------- */

const CRITICAL_SPECS = [
  // display (hero H1, .display numerals)
  '800 1rem "PP Neue Machina Inktrap"',
  '400 1rem "PP Neue Machina Inktrap"',
  // headings / nav / pills
  '800 1rem "PP Neue Machina Plain"',
  '400 1rem "PP Neue Machina Plain"',
  // body, semibold and extrabold runs
  '400 1rem "PP Neue Montreal"',
  '600 1rem "PP Neue Montreal"',
  '800 1rem "PP Neue Montreal"',
  // dense reading + the accent face kickers/telemetry use
  '400 1rem "PP Neue Montreal Text"',
  '600 1rem "Space Grotesk Variable"',
];

/** Resolves when every critical face is loaded — or when `timeoutMs` says
 *  the network is not going to answer. Never rejects. */
export function criticalFontsReady(timeoutMs = 1500): Promise<void> {
  if (typeof document === 'undefined' || !document.fonts) return Promise.resolve();
  const loading = Promise.all(CRITICAL_SPECS.map((spec) => document.fonts.load(spec))).then(
    () => undefined,
    () => undefined,
  );
  const timeout = new Promise<void>((resolve) => window.setTimeout(resolve, timeoutMs));
  return Promise.race([loading, timeout]);
}
