#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# generate-art-variants.sh — build-time art pipeline (ImageMagick).
#
# For every source JPG in public/art/ this emits:
#   · <name>-<w>.avif  — responsive AVIF renditions (w = 540 / 840, portrait;
#                        960 for the landscape hero)
#   · <name>.avif      — full-width AVIF rendition (fallback-free browsers
#                        never touch the JPEG again)
#   · <name>-lqip.webp — 24px-wide blur-up placeholder (inlined as base64
#                        into src/lib/art-variants.ts by this same script)
#
# Re-run after replacing placeholder art in public/art/. Requires
# ImageMagick 7 with the AVIF/WebP delegates.
# ---------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")/.."

PORTRAIT_WIDTHS=(540 840)
HERO_WIDTHS=(960)

for src in public/art/*.jpg; do
  base="$(basename "$src" .jpg)"
  w=$(identify -format '%w' "$src")

  widths=("${PORTRAIT_WIDTHS[@]}")
  [[ "$base" == "hero" ]] && widths=("${HERO_WIDTHS[@]}")

  for width in "${widths[@]}"; do
    if (( w > width )); then
      convert "$src" -resize "${width}x" -quality 50 "public/art/${base}-${width}.avif"
    fi
  done
  # full-size AVIF rendition
  convert "$src" -quality 50 "public/art/${base}.avif"
  # LQIP: 24px wide, cheap webp (base64-inlined by the TS generator below)
  convert "$src" -resize 24x -quality 40 "public/art/${base}-lqip.webp"
done

# Emit the TS module: srcset strings + inline LQIP data URIs.
out="src/lib/art-variants.ts"
{
  echo '/**'
  echo ' * GENERATED by scripts/generate-art-variants.sh — do not edit by hand.'
  echo ' * Re-run after replacing placeholder art in public/art/.'
  echo ' */'
  echo ''
  echo 'const BASE = `${import.meta.env.BASE_URL}art/`;'
  echo ''
  echo '/* AVIF srcset per source name (density-appropriate widths). */'
  echo 'export const ART_SRCSET: Record<string, string> = {'
  for src in public/art/*.jpg; do
    base="$(basename "$src" .jpg)"
    full=$(identify -format '%w' "$src")
    entries=""
    if [[ "$base" == "hero" ]]; then
      [[ -f "public/art/${base}-960.avif" ]] && entries="    \${BASE}${base}-960.avif 960w,"
    else
      [[ -f "public/art/${base}-540.avif" ]] && entries="    \${BASE}${base}-540.avif 540w,"
      [[ -f "public/art/${base}-840.avif" ]] && entries="$entries
    \${BASE}${base}-840.avif 840w,"
    fi
    echo "  '$base.jpg': \`"
    [[ -n "$entries" ]] && echo "$entries"
    echo "    \${BASE}${base}.avif ${full}w
  \`,"
  done
  echo '};'
  echo ''
  echo '/* Inline blur-up placeholders — 24px WebP, sub-1KB each. */'
  echo 'export const ART_LQIP: Record<string, string> = {'
  for src in public/art/*.jpg; do
    base="$(basename "$src" .jpg)"
    b64=$(base64 -w0 "public/art/${base}-lqip.webp")
    echo "  '$base.jpg': 'data:image/webp;base64,$b64',"
  done
  echo '};'
} > "$out"

echo "wrote $out"
